[project]
name = "proposal-device"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.proposal-registry]
path = "contracts/proposal-registry.clar"
depends_on = []

[contracts.voting-escrow]
path = "contracts/voting-escrow.clar"
depends_on = []

[contracts.proposal-reputation]
path = "contracts/proposal-reputation.clar"
depends_on = []

[contracts.proposal-tracking]
path = "contracts/proposal-tracking.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
